project_id = "ilemfubbtpmfzjtcniel"

[functions.onboard-goal]
verify_jwt = true

[functions.reschedule-task]
verify_jwt = true

[functions.delete-and-refactor-plan]
verify_jwt = true

[functions.generate-plan]
verify_jwt = true

[functions.verify-google-purchase]
verify_jwt = true