project_id = "ilemfubbtpmfzjtcniel"

[functions.onboard-goal]
verify_jwt = true

[functions.reschedule-task]
verify_jwt = true

[functions.delete-and-refactor-plan]
verify_jwt = true

[functions.generate-plan]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.verify-subscription]
verify_jwt = true

[functions.record-purchase]
verify_jwt = true