// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ilemfubbtpmfzjtcniel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZW1mdWJidHBtZnpqdGNuaWVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTE3ODUsImV4cCI6MjA3MDQ4Nzc4NX0.MaSq-FUlq3tUSSevY5-6A-0zdq6UuFtndJC5gRIs3hM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});